# Roche SEIR Model

In this notebook we present compare the model built by F. Hoffmann-La Roche Ltd with a simple SEIR. We aim to see if the Roche model can be reduced to a simple SEIR model for appropriate choices of parameters to check how well the Roche model has been reproduced.

The analyses are run for:
 - Dates: **15 Feb 2020** - **15 May 2020**, using toy data;
 - PHE regions of interest: **South West**.

We consider only **1 region** and **1 age group**. To be able to collapse the Roche model in a simpler SEIR version, we will have to choose the parameters such that:

$$
\begin{align*}
    \frac{dS(t)}{dt} &= C(- \frac{\beta_a}{N} S(t)
        I^a(t) - \frac{\beta_{aa}}{N} S(t) I^{aa}(t) -
        \frac{\beta_s}{N} S(t) I^s(t) - \frac{\beta_{as}}{N} S(t)
        I^{as}(t) - \frac{\beta_{aas}}{N} S(t) I^{aas}(t) -
        \frac{\beta_{ss}}{N} S(t) I^{ss}(t)) \\
    \frac{dE(t)}{dt} &= -\gamma_E E(t) + C(
        \frac{\beta_a}{N} S(t) I^a(t) + \frac{\beta_{aa}}{N} S(t)
        I^{aa}(t) + \frac{\beta_s}{N} S(t) I^s(t) +
        \frac{\beta_{as}}{N} S(t) I^{as}(t) + \frac{\beta_{aas}}{N}
        S(t) I^{aas}(t) + \frac{\beta_{ss}}{N} S(t) I^{ss}(t)) \\
    \frac{dI^a(t)}{dt} &= (1 - P_{ss}) \gamma_E E(t) -
        \gamma_s I^a(t) \\
    \frac{dI^{aa}(t)}{dt} &= P_a \gamma_s I^a(t) -
        \gamma_{ra} I^{aa}(t) \\
    \frac{dI^s(t)}{dt} &= (1 - P_a) \gamma_s I^a(t) -
        \gamma_q I^s(t) \\
    \frac{dI^{as}(t)}{dt} &= P_{ss} \gamma_E E(t) -
        \gamma_s I^{as}(t) \\
    \frac{dI^{aas}(t)}{dt} &= P_a \gamma_s I^{as}(t) -
        \gamma_{ra} I^{aas}(t) \\
    \frac{dI^{ss}(t)}{dt} &= (1 - P_a) \gamma_s I^{as}(t) -
        \gamma_q I^{ss}(t) \\
    \frac{dI^q(t)}{dt} &= \gamma_q I^{ss}(t) + \gamma_q I^s(t) -
        \gamma_r I^q(t)\\
    \frac{dR(t)}{dt} &= (1 - P_d) \gamma_r I^q(t) \\
    \frac{dR^a(t)}{dt} &= \gamma_{ra} I^{aas}(t) +
        \gamma_{ra} I^{aa}(t) \\
    \frac{dD(t)}{dt} &= P_d \gamma_r I^q(t)
\end{align*}
$$

becomes

$$
\begin{align*}
    \frac{dS(t)}{dt} &= - \beta I(t) S(t) \\
    \frac{dE(t)}{dt} &= \beta I(t) S(t) - \kappa E(t) \\
    \frac{dI(t)}{dt} &= \kappa E(t) - \gamma I(t) \\
    \frac{dR(t)}{dt} &= \gamma I(t)
\end{align*}
$$

We have multiple infectious compartments in the Roche model: asymptomatic, symptomatic, quarantined and presymptomatic, normal or superspreader, compared to only one in the SEIR one. Similarly, the Roche model distinguishes between recovered individuals that were symptomatic or asymptomatic during their infectious period. Moreover, the Roche model also includes a compartment for the dead, not present in the simple SEIR model.

The flow into each of these compartments is regulated through the parameters $P_a$, $P_{ss}$ and $P_d$.

The transmission rates into the exposed compartment in the Roche model are hard-coded to be computed as:
$$
\begin{align*}
    \beta_a &= \beta_{aa} = \frac{\beta_s}{2} \\
    \beta_{as} &= \beta_{aas} = \frac{\beta_{ss}}{2} \\
    \beta_{s} &= \beta_{max} - (\beta_{max} - \beta_{min})\frac{
        SI^\gamma}{SI^\gamma + SI_{50}^\gamma} \\
    \beta_{as} &= (1 + b_{ss})\beta_a \\
    \beta_{aas} &= (1 + b_{ss})\beta_{aa} \\
    \beta_{ss} &= (1 + b_{ss})\beta_s \\
\end{align*}
$$

Therefore, we cannot keep the asymptomatic and symptomatic. We will turn off the symptomatic transmission.

We therefore need to turn down all the parameters related to symptomatic or super-spreader infections to account only for symptomatic infections:

$P_{ss} = P_d = 0$ and $P_a = 1$.

The Roche model ODE system will then look like:

$$
\begin{align*}
    \frac{dS(t)}{dt} &= C(- \frac{\beta_a}{N} S(t)
        I^a(t) - \frac{\beta_{aa}}{N} S(t) I^{aa}(t) -
        \frac{\beta_s}{N} S(t) I^s(t) - \frac{\beta_{as}}{N} S(t)
        I^{as}(t) - \frac{\beta_{aas}}{N} S(t) I^{aas}(t) -
        \frac{\beta_{ss}}{N} S(t) I^{ss}(t)) \\
    \frac{dE(t)}{dt} &= -\gamma_E E(t) + C(
        \frac{\beta_a}{N} S(t) I^a(t) + \frac{\beta_{aa}}{N} S(t)
        I^{aa}(t) + \frac{\beta_s}{N} S(t) I^s(t) +
        \frac{\beta_{as}}{N} S(t) I^{as}(t) + \frac{\beta_{aas}}{N}
        S(t) I^{aas}(t) + \frac{\beta_{ss}}{N} S(t) I^{ss}(t)) \\
    \frac{dI^a(t)}{dt} &= \gamma_E E(t) - \gamma_s I^a(t) \\
    \frac{dI^{aa}(t)}{dt} &= \gamma_s I^a(t) - \gamma_{ra} I^{aa}(t)\\
    \frac{dI^s(t)}{dt} &= - \gamma_q I^s(t) \\
    \frac{dI^{as}(t)}{dt} &= - \gamma_s I^{as}(t) \\
    \frac{dI^{aas}(t)}{dt} &= \gamma_s I^{as}(t) - \gamma_{ra} I^{aas}(t) \\
    \frac{dI^{ss}(t)}{dt} &= - \gamma_q I^{ss}(t) \\
    \frac{dI^q(t)}{dt} &= \gamma_q I^{ss}(t) + \gamma_q I^s(t) -
        \gamma_r I^q(t)\\
    \frac{dR(t)}{dt} &= \gamma_r I^q(t) \\
    \frac{dR^a(t)}{dt} &= \gamma_{ra} I^{aas}(t) +
        \gamma_{ra} I^{aa}(t) \\
    \frac{dD(t)}{dt} &= 0
\end{align*}
$$

The previous set of ODEs indicate that we have a constant number of dead. To turn off completely this compartment, along with all the other symptomatic recovered and symptomatic normal, quarantined and all super-spreader infectives ones, we impose constrained initial conditions:

$$
I^s(0) = I^{as}(0) = I^{aas}(0) = I^{ss}(0) = I^q(0) = R(0) = D(0) = 0
$$

These assumption conclude that $I^s(t) = I^{as}(t) = I^{aas}(t) = I^{ss}(t) = I^q(t) = R(t) = D(t) = 0, \forall t$. Thus, the final form of the Roche model looks like:

$$
\begin{align*}
    \frac{dS(t)}{dt} &= C(- \frac{\beta_a}{N} S(t)
        I^a(t) - \frac{\beta_{aa}}{N} S(t) I^{aa}(t)) \\
    \frac{dE(t)}{dt} &= -\gamma_E E(t) + C(
        \frac{\beta_a}{N} S(t) I^a(t) +  \frac{\beta_{aa}}{N} S(t) I^{aa}(t)) \\
    \frac{dI^a(t)}{dt} &= \gamma_E E(t) - \gamma_s I^a(t) \\
    \frac{dI^{aa}(t)}{dt} &= \gamma_s I^a(t) - \gamma_{ra} I^{aa}(t) \\
    \frac{dR^a(t)}{dt} &= \gamma_{ra} I^{aa}(t)
\end{align*}
$$

We still are left with 2 infectious compartments: presymptomatic ($I^a$) and asymptomatic ($I^{aa}$). This is good as we assume in the Roche model there are no differences in transmission of the virus between asymptomatic and presymptomatic cases, i.e. $\beta_a = \beta_{aa}$. Hence, we will assume a collapse of this structure, by using the following notation: $I(t) = I^a(t) + I^{aa}(t)$ and $R(t) = R^a(t)$. The compressed Roche model becomes (drop the superscript for R):

$$
\begin{align*}
    \frac{dS(t)}{dt} &= - C \frac{\beta_a}{N} S(t) (I^a(t) + I^{aa}(t)) = - C \frac{\beta_a}{N} S(t) I(t) =
         - C \frac{\beta_s}{2N} S(t) I(t) \\
    \frac{dE(t)}{dt} &= -\gamma_E E(t) + C \frac{\beta_s}{2N} S(t) I(t) \\
    \frac{dI(t)}{dt} &= \gamma_E E(t) - \gamma_{ra} I^{aa}(t) \\
    \frac{dR(t)}{dt} &= \gamma_{ra} I^{aa}(t)
\end{align*}
$$

We deal now with the other parameters of the model:
$$
\begin{align*}
    \gamma_E &= \frac{1}{k} \\
    \gamma_s &= \frac{1}{k_s} \\
    \gamma_q &= \frac{1}{k_q} \\
    \gamma_r &= \frac{1}{k_r} \\
    \gamma_{ra} &= \frac{1}{k_{ri}} \\
\end{align*}
$$

Also, since the rate of transmission between the compartments are defined as the inverse of the average time spent in the compartment, the system of equations of the Roche model illustrate that an individual spends on average in each of the infectious compartments are:

$I^a$ and $I^{aa}$: $k_s$ and $k_{ri}$ respectively, so a total average of $k_s + k_{ri}$ as infectious.

Still, the two models are still not exchangeable yet. One more assumption that we will make is that the average time people are presymptomatic is very small, so that $I(t) \approx I^{aa}(t), \forall t$. This means that we take $k_s \ll 1$.

Hence, for the SEIR model, the parameters are defined as:

$$
\begin{align*}
    \beta &= C \frac{\beta_s}{2N} = C \frac{\beta_{max} - (\beta_{max} - \beta_{min})\frac{
            SI^\gamma}{SI^\gamma + SI_{50}^\gamma}}{2N} \\
    \kappa &= \gamma_E =  \frac{1}{k}\\
    \gamma &= \frac{1}{k_s + k_{ri}}
\end{align*}
$$

Moreover, since the parameters of the SEIR model are time-independent, so must be the transition rates in the Roche model. Hence no change is taken in the levels of the NPIs present.

*The Roche model is built by F. Hoffmann-La Roche Ltd.*

In [1]:
# Load necessary libraries
import os
import numpy as np
import pandas as pd
from scipy.integrate import solve_ivp
import epimodels as em
import pints
import matplotlib
import plotly.graph_objects as go
from matplotlib import pyplot as plt
from iteration_utilities import deepflatten
from itertools import chain

## Model Setup
### Define setup matrices for the Roche Model

In [2]:
# Populate the model
total_days =  90
regions = ['SW']
age_groups = ['0-75+']

matrices_region = []

### Fixed
# Initial state of the system
weeks_matrices_region = []
for r in regions:
    path = os.path.join('../../data/final_contact_matrices/BASE.csv')
    region_data_matrix = np.average(pd.read_csv(path, header=None, dtype=np.float64)) * np.ones((len(age_groups), len(age_groups)))
    regional = em.RegionMatrix(r, age_groups, region_data_matrix)
    weeks_matrices_region.append(regional)

matrices_region.append(weeks_matrices_region)

contacts = em.ContactMatrix(age_groups, np.ones((len(age_groups), len(age_groups))))
matrices_contact = [contacts]

# Matrices contact
time_changes_contact = [1]
time_changes_region = [1]

# NPIs data
max_levels_npi = [3, 3, 2, 4, 2, 3, 2, 4, 2]
targeted_npi = [True, True, True, True, True, True, True, False, True]
general_npi = [[False, False, False, False, False, False, False, False, False]]
time_changes_flag = [1]

reg_levels_npi = [
    [[0, 0, 0, 0, 0, 0, 0, 0, 0]]]
time_changes_npi = [1]

### Set the parameters and initial conditions of the model and bundle everything together

In [3]:
# Instantiate model
roche_model = em.RocheSEIRModel()

# Set the region names, contact and regional data of the model
roche_model.set_regions(regions)
roche_model.set_age_groups(age_groups)
roche_model.read_contact_data(matrices_contact, time_changes_contact)
roche_model.read_regional_data(matrices_region, time_changes_region)
roche_model.read_npis_data(max_levels_npi, targeted_npi, general_npi, reg_levels_npi, time_changes_npi, time_changes_flag)

# Set ICs parameters
ICs = em.RocheICs(
    model=roche_model,
    susceptibles_IC=[[5000]],
    exposed_IC=[[0]],
    infectives_pre_IC=[[70]],
    infectives_asym_IC=[[0]],
    infectives_sym_IC=[[0]],
    infectives_pre_ss_IC=[[0]],
    infectives_asym_ss_IC=[[0]],
    infectives_sym_ss_IC=[[0]],
    infectives_q_IC=[[0]],
    recovered_IC=[[0]],
    recovered_asym_IC=[[0]],
    dead_IC=[[0]]
)

# Set average times in compartments
compartment_times = em.RocheCompartmentTimes(
    model=roche_model,
    k=4,
    kS=0.0001, # average time as presymptomatic is << 1
    kQ=1,
    kR=3,
    kRI=4
)

# Set proportion of asymptomatic, super-spreader and dead cases
proportion_parameters = em.RocheProportions(
    model=roche_model,
    Pa=1,
    Pss=0,
    Pd=0
)

# Set transmission parameters
transmission_parameters = em.RocheTransmission(
    model=roche_model,
    beta_min=0.228,
    beta_max=2.176,
    bss=3.11,
    gamma=1,
    s50=35.3
)

# Set other simulation parameters
simulation_parameters = em.RocheSimParameters(
    model=roche_model,
    region_index=1,
    method='RK45',
    times=np.arange(1, total_days, 1).tolist()
)

# Set all parameters in the controller
roche_parameters = em.RocheParametersController(
    model=roche_model,
    ICs=ICs,
    compartment_times=compartment_times,
    proportion_parameters=proportion_parameters,
    transmission_parameters=transmission_parameters,
    simulation_parameters=simulation_parameters
)

### Define SEIR model

In [4]:
class SEIRModel(pints.ForwardModel):
    r"""
    ODE model: deterministic SEIR
    The SEIR Model has four compartments:
    susceptible individuals (:math:`S`),
    exposed but not yet infectious (:math:`E`),
    infectious (:math:`I`) and recovered (:math:`R`):

    .. math::
        \frac{dS(t)}{dt} = -\beta S(t)I(t),
    .. math::
        \frac{dE(t)}{dt} = \beta S(t)I(t) - \kappa E(t),
    .. math::
        \frac{dI(t)}{dt} = \kappa E(t) - \gamma I(t),
    .. math::
        \frac{dR(t)}{dt} = \gamma I(t),

    where :math:`S(0) = S_0, E(0) = E_0, I(O) = I_0, R(0) = R_0`
    are also parameters of the model.

    Extends :class:`ForwardModel`.
    """

    def __init__(self):
        super(SEIRModel, self).__init__()

        # Assign default values
        self._output_names = ['S', 'E', 'I', 'R', 'Incidence']
        self._parameter_names = [
            'S0', 'E0', 'I0', 'R0', 'alpha', 'beta', 'gamma'
        ]
        # The default number of outputs is 5,
        # i.e. S, E, I, R and Incidence
        self._n_outputs = len(self._output_names)
        # The default number of outputs is 7,
        # i.e. 4 initial conditions and 3 parameters
        self._n_parameters = len(self._parameter_names)

        self._output_indices = np.arange(self._n_outputs)

    def n_outputs(self):
        # Return the number of outputs
        return self._n_outputs

    def n_parameters(self):
        # Return the number of parameters
        return self._n_parameters

    def output_names(self):
        # Return the (selected) output names
        names = [self._output_names[x] for x in self._output_indices]
        return names

    def parameter_names(self):
        # Return the parameter names
        return self._parameter_names

    def set_outputs(self, outputs):
        # Check existence of outputs
        for output in outputs:
            if output not in self._output_names:
                raise ValueError(
                    'The output names specified must be in correct forms')

        output_indices = []
        for output_id, output in enumerate(self._output_names):
            if output in outputs:
                output_indices.append(output_id)

        # Remember outputs
        self._output_indices = output_indices
        self._n_outputs = len(outputs)

    def _right_hand_side(self, t, y, c):
        # Assuming y = [S, E, I, R] (the dependent variables in the model)
        # Assuming the parameters are ordered like
        # parameters = [S0, E0, I0, R0, beta, kappa, gamma]
        # Let c = [beta, kappa, gamma]
        #  = [parameters[0], parameters[1], parameters[2]],
        # then beta = c[0], kappa = c[1], gamma = c[2]

        # Construct the derivative functions of the system of ODEs

        s, e, i, _ = y
        beta, kappa, gamma = c
        dydt = [-beta * s * i, beta * s * i - kappa * e,
                kappa * e - gamma * i, gamma * i]

        return dydt

    def simulate(self, parameters, times):

        # Define time spans, initial conditions, and constants
        y_init = list(deepflatten(parameters[:4]))
        c = list(deepflatten(parameters[4:]))

        # Solve the system of ODEs
        sol = solve_ivp(lambda t, y: self._right_hand_side(t, y, c),
                        [times[0], times[-1]], y_init, t_eval=times)

        output = sol['y']

        # Total infected is infectious 'i' plus recovered 'r'
        total_infected = output[2, :] + output[3, :]

        # Number of incidences is the increase in total_infected
        # between the time points (add a 0 at the front to
        # make the length consistent with the solution
        n_incidence = np.zeros(len(times))
        n_incidence[1:] = total_infected[1:] - total_infected[:-1]

        # Append n_incidence to output
        # Output is a matrix with rows being S, E, I, R and Incidence
        output = np.vstack(tup=(output, n_incidence))

        # Get the selected outputs
        output = output[self._output_indices, :]

        return output.transpose()


### Set the parameters and initial conditions of the model and bundle everything together

In [5]:
# Instantiate model
seir_model = SEIRModel()

# Set all parameters
S0 = np.int64(np.asarray(roche_parameters.ICs.susceptibles))
E0 = np.int64(np.asarray(roche_parameters.ICs.exposed))
I0 = np.int64(np.asarray(roche_parameters.ICs.infectives_pre)) + np.int64(np.asarray(roche_parameters.ICs.infectives_asym))
R0 = np.int64(np.asarray(roche_parameters.ICs.recovered_asym))

total_pop = np.int64(np.asarray(roche_parameters.ICs.susceptibles))+ np.int64(np.asarray(roche_parameters.ICs.exposed))+ \
                + np.int64(np.asarray(roche_parameters.ICs.infectives_pre))+ np.int64(np.asarray(roche_parameters.ICs.infectives_asym))+ \
                + np.int64(np.asarray(roche_parameters.ICs.infectives_sym))+ np.int64(np.asarray(roche_parameters.ICs.infectives_pre_ss))+ \
                + np.int64(np.asarray(roche_parameters.ICs.infectives_asym_ss))+ np.int64(np.asarray(roche_parameters.ICs.infectives_sym_ss))+ \
                + np.int64(np.asarray(roche_parameters.ICs.infectives_q))+ np.int64(np.asarray(roche_parameters.ICs.recovered))+ \
                + np.int64(np.asarray(roche_parameters.ICs.recovered_asym))+ np.int64(np.asarray(roche_parameters.ICs.dead))

SI = roche_model._compute_SI(1, 1)

fraction = (SI ** roche_parameters.transmission_parameters.gamma) / \
    (roche_parameters.transmission_parameters.s50 ** roche_parameters.transmission_parameters.gamma + \
     SI ** roche_parameters.transmission_parameters.gamma)

beta_s = roche_parameters.transmission_parameters.beta_max - fraction * (roche_parameters.transmission_parameters.beta_max - roche_parameters.transmission_parameters.beta_min)

denominator = np.float64(np.asarray(roche_model.matrices_region[0][0]._data)) * beta_s

beta = denominator / (2 * total_pop)
kappa = 1/roche_parameters.compartment_times.k
gamma = 1/(roche_parameters.compartment_times.kS + roche_parameters.compartment_times.kRI)

seir_parameters = [S0, E0, I0, R0, beta, kappa, gamma]

/var/folders/ph/jyxnc9y52svgq2k5lt2q4r000000gp/T/ipykernel_35584/3943490555.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  denominator = np.float64(np.asarray(roche_model.matrices_region[0][0]._data)) * beta_s


In [6]:
seir_parameters

[array([[5000]]),
 array([[0]]),
 array([[70]]),
 array([[0]]),
 array([[0.00011082]]),
 0.25,
 array([0.24999375])]

### Simulate for one of the regions: **South West**

In [7]:
# Simulate the PHE model using the ODE solver from scipy
ext_output_roche_model = roche_model.simulate(roche_parameters)
output_roche_model = np.stack((ext_output_roche_model[:, 0], ext_output_roche_model[:, 1], ext_output_roche_model[:, 2] + ext_output_roche_model[:, 3], ext_output_roche_model[:, -3], ext_output_roche_model[:, -1]), axis=1)

# Simulate the SEIR model using the ODE solver from scipy
output_seir_model = seir_model.simulate(seir_parameters, times=roche_parameters.simulation_parameters.times)

## Plot the comparments of the two models against each other
### Setup ``plotly`` and default settings for plotting

In [8]:
from plotly.subplots import make_subplots

colours = ['blue', 'red', 'green', 'purple', 'orange', 'black', 'gray', 'pink']

# Group outputs together
outputs = [output_roche_model, output_seir_model]

### Plot the comparments of the two models against each other

In [9]:
# Trace names - represent the solver used for the simulation
trace_name = ['Roche model', 'SEIR model']

# Compartment list - type and age
comparments = []
for n in seir_model.output_names():
    comparments.append('{}'.format(n))

fig = go.Figure()
fig = make_subplots(
    rows=int(np.ceil(len(comparments)/2)), cols=2, subplot_titles=tuple('{}'.format(comparment) for comparment in comparments)
)

# Plot for each comparment
for c, comparment in enumerate(comparments):
    # Plot (line plot for each solver method for each age)
    for a, age in enumerate(age_groups):
        if c != 0:
            for o, out in enumerate(outputs):
                fig.add_trace(
                    go.Scatter(
                        y=out[:, c*len(age_groups)+a],
                        x=roche_parameters.simulation_parameters.times,
                        mode='lines',
                        name=trace_name[o],
                        line_color=colours[o],
                        showlegend=False
                    ),
                    row= int(np.floor(c / 2)) + 1,
                    col= c % 2 + 1
                )
        
        else:
            for o, out in enumerate(outputs):
                fig.add_trace(
                    go.Scatter(
                        y=out[:, c*len(age_groups)+a],
                        x=roche_parameters.simulation_parameters.times,
                        mode='lines',
                        name=trace_name[o],
                        line_color=colours[o]
                    ),
                    row= int(np.floor(c / 2)) + 1,
                    col= c % 2 + 1
                )

# Add axis labels
fig.update_layout(
    boxmode='group',
    title='Roche vs SEIR Model', 
    width=900, 
    height=800,
    plot_bgcolor='white',
    xaxis=dict(linecolor='black', title='Time (days)'),
    yaxis=dict(linecolor='black'),
    xaxis2=dict(linecolor='black', title='Time (days)'),
    yaxis2=dict(linecolor='black'),
    xaxis3=dict(linecolor='black', title='Time (days)'),
    yaxis3=dict(linecolor='black'),
    xaxis4=dict(linecolor='black', title='Time (days)'),
    yaxis4=dict(linecolor='black'),
    xaxis5=dict(linecolor='black', title='Time (days)'),
    yaxis5=dict(linecolor='black'))

fig.write_image('images/Roche_SEIR.pdf')
fig.show()